name: Build Folia v3

on:
  push:
    branches:
      - feature/folia-v3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build project
      - name: Build with Gradle
        run: ./gradlew clean build

      # Step 4: Archive built files
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: worldedit-bukkit/build/libs/*
